### ISSUE TITLE
Error in charges search when creating arms

### ISSUE THREAD

**Issue by PLFaure** [heraldry/armory#3]
There is an issue when I try to add new charges for my coat of arms. The error happens:
- When I type in the search bar from the "select charge" panel
- When I click on a charge directly in the tree

Here is the screenshot from the console:

![image](https://user-images.githubusercontent.com/12431011/127187081-3cd5b403-b9a6-4328-be15-e54de24d5594.png)

**Comment by or** [comment]
I could reproduce that, it was entirely broken. Should work again now (might have to do a hard refresh to grab the latest JS).
Thanks for reporting!

Please reopen if it still misbehaves.
