### ISSUE TITLE
Escutcheon shadow blurry in Safari

### ISSUE THREAD

**Issue by mirnovov** [heraldry/armory#4]
When the `Escutcheon shadow (ignored for export)` option is enabled in Safari, the resulting image is rather blurry:
![Untitled](https://user-images.githubusercontent.com/73574818/173971520-7e514b80-9c0f-45d0-8d7a-ff6191633627.jpg)

This seems to be something to do with [how Safari handles SVG filters](https://stackoverflow.com/questions/47942581/svg-filters-fuzzy-in-safari-under-some-circumstances), and should be a quick fix by specifying a correct `filterRes`.

**Comment by or** [comment]
This issues slipped through the cracks in the past months. Thanks for the SO link, that was helpful.
The percentage values already seemed correct and `filterRes` had no effect, but changing them to absolute numbers improved the situation.

Safari still does some strange things, as the pattern (if the field is ermine, for instance) shifts slightly when the filter is turned on, but that's strange. And it still looks a little less sharp than on Chrome.

At any rate, it's improved now, cheers.
